# Generated by Django 4.2.4 on 2023-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_add_genericsettings_and_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="title_suffix",
            field=models.CharField(
                default="Aurélie Clodic",
                help_text="The suffix for the title meta tag e.g. ' | The Wagtail Bakery'",
                max_length=255,
                verbose_name="Title suffix",
            ),
        ),
    ]
